authentication/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LogoutView

app_name = 'authentication'

urlpatterns = [
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('blog:homepage')), name="logout"),
]

blog/urls.py
from django.urls import path, include
from .views import PostListView, PostDetailView, PostCreateView
from django.shortcuts import redirect

app_name = 'blog'

urlpatterns = [
    path('', lambda req: redirect('blog:post_list')),
    path('posts/', PostListView.as_view(), name="post_list"),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name="post_detail"),
    path('add-post/', PostCreateView.as_view(), name="post_form"),

]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #add this
from django.conf.urls.static import static #add this
from blog.views import Error404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404.as_view()

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

blog/models.py
from django.db import models
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, null=True, blank=True, unique=True)
    thumbnail = models.ImageField(upload_to="images", null=True, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextUploadingField(blank=True, null=True)
    snippet = models.CharField(max_length=200, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class PostSearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)

authentication/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Post
from .forms import PostSearchForm
from django.db.models import Q

# Create your views here.


class Error404(TemplateView):
    template_name = "blog/404.html"


class PostListView(ListView):
    paginate_by = 4
    model = Post
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = PostSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        form = PostSearchForm(self.request.GET)
        if form.is_valid():
            query = Q(title__icontains=form.cleaned_data['query'])
            return Post.objects.filter(query)
        return Post.objects.all()


class PostDetailView(DetailView):
    model = Post


class PostCreateView(CreateView, LoginRequiredMixin):
    model = Post
    fields = '__all__'

"""
class PostUpdateView(UpdateView, LoginRequiredMixin):
    model = Post


class PostDeleteView(DeleteView):
    model = Post
"""

blog/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/css/styles.css" rel="stylesheet"/>
</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">Janko Tech Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Blog</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" aria-current="page"
                                            href="{% url 'admin:index' %}">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" aria-current="page"
                                            href="{% url 'authentication:logout' %}">Logout</a></li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page content-->
<div class="container">
    <div class="row mt-3 mb-3">
        <!-- Blog entries-->
        <div class="col-lg-8">
            <!-- Featured blog post-->

            <!-- Nested row for non-featured blog posts-->


            <div class="row">
                {% block content %}
                {% endblock %}

            </div>

        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            {% block widget %}
            {% endblock %}


            <div class="card mb-4">
                <div class="card-header">About me <i class="bi bi-person-circle"></i></div>
                <div class="card-body">My name is Janko Častvan and I am interested in technology.</div>
            </div>
            <div class="card mb-4">
                <div class="card-header">Twitter feed <i class="bi bi-twitter"></i></div>
                <div class="card-body"><a class="twitter-timeline" data-height="500"
                                          href="https://twitter.com/JankoTFCG1996?ref_src=twsrc%5Etfw">Tweets by
                    JankoTFCG1996</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Janko Tech Blog 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="/static/js/scripts.js"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "_layout.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <article>
        <h1>{{ post.title }}</h1>
        <p>{{ post.created_on }}</p>

        {{ post.content | safe }}
    </article>
    <div id="disqus_thread"></div>
    <script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

    var disqus_config = function () {
    // this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = {{ post.slug }}; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://http-127-0-0-1-8000-ydrybmlfx0.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();

    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "_layout.html" %}
{% block title %}Add post{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layout.html" %}
{% block title %}Blog{% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="col-lg-6">
            <!-- Blog post-->
            <div class="card mb-4">
                {% if post.thumbnail %}
                <a href="#!"><img class="card-img-top" src="{{ post.thumbnail.url }}"
                                  alt="..."/></a>
                {% endif %}
                <div class="card-body">
                    <div class="small text-muted"><i class="bi bi-calendar"></i> {{ post.created_on }}</div>
                    <h2 class="card-title h4">{{ post.title }}</h2>
                    <p class="card-text">{{ post.snippet }}</p>
                    <a class="btn btn-dark" href="{% url 'blog:post_detail' post.slug %}">Read more</a>
                </div>
            </div>
            <!-- Blog post-->

        </div>
    {% endfor %}

    <!-- Pagination-->

    <div class="row text-center mb-10">
        <div class="col mb-10">
         <span>
    {% if page_obj.has_previous %}
        <a class="btn btn-dark" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
             <span>
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
             {% if page_obj.has_next %}
                 <a class="btn btn-dark" href="?page={{ page_obj.next_page_number }}">Next</a>
             {% endif %}
  </span>

        </div>

    </div>

{% endblock %}

{% block widget %}

    <div class="card mb-4">
        <div class="card-header">Search <i class="bi bi-search"></i></div>
        <div class="card-body">
            <form method="get" action="{% url 'blog:post_list' %}" class="form-inline">
                {{ form.query }}
                <button type="submit" class="btn btn-dark"><i class="bi bi-search"></i></button>
            </form>
        </div>
    </div>
{% endblock %}